version: "3"

services:

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  ping:
    build:
      context: ./ping
    ports:
      - "5000:5000"

  pong:
    build:
      context: ./pong
    ports:
      - "4000:4000"
