service: my-gcloud-service

provider:
  name: google
  runtime: 'nodejs10'
  project: 'cs3219-otot-task-b'
  credentials: ~/.gcloud/keyfile.json # path must be absolute

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  TaskB3:
    handler: app
    events:
      - http: path
